version: '3.3'

services:

  app:
    image: gcr.io/randomized-controlled-trials/app:latest
    build:
      context: .
    ports:
      - 8081:80
      - 8444:443
    # DEV:
    volumes:
       - ./src:/var/www/html
    # /DEV
    links:
      - 'db'

  db:
    image: mariadb:10.5
    ports:
      - 3307:3306
    volumes:
      - ./db/db_init.sql:/docker-entrypoint-initdb.d/00_db_init.sql
      - ./db/db_sample_6fdc.sql:/docker-entrypoint-initdb.d/10_db_populate.sql
      # - ./db/mariadb:/var/lib/mysql
    environment:
      TZ: 'America/Chicago'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'rooot'
      MYSQL_DATABASE: 'rctrials'
      MYSQL_USER: 'rctrials-db-user'
      MYSQL_PASSWORD: 'rctrials-db-pass'
